### ISSUE TITLE
Any example code on how to use this?

### ISSUE THREAD

**Issue by IAmOrion** [fust/ArduinoELM327#1]
As per title, Is there example code on how to use this please?

**Comment by fust** [comment]
There is not.
As is stated in the README this project is (or better was) a work-in-progress project.
I have decided to not put any effort in further developing and maintaining this library as it practically mirrors the Freematics OBD library (https://github.com/stanleyhuangyc/ArduinoOBD).
You can check out my fork which supports adding additional init strings here: https://github.com/fust/ArduinoOBD
